# Generated by Django 4.1.7 on 2023-03-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="signup",
            fields=[
                ("sno", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=12)),
            ],
        ),
    ]
