# Generated by Django 4.1.7 on 2023-03-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0004_rename_tasks_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
